default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: '1.1.0'
    hooks:
      - id: sync_with_poetry
        args: []
        additional_dependencies: ['poetry']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
